version: '3.8'
services:
  mangoread:
    build: ./mangoread
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./mangoread:/usr/src/app
    ports:
      - 8080:8080