# Generated by Django 4.1.5 on 2023-01-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_manga_genre_manga_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='genre',
            field=models.ManyToManyField(related_name='manga_genre', to='main.genre'),
        ),
    ]
